### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [BrandoBie/10_Model#1]
It looks like all I see on the Heroku app is a message that `Welcome To cats-R-here.com, At this time our HOME PAGE is down for maintenance.` And the only link I see is to the home page (the page I'm on).

**Comment by BrandoBie** [comment]
Fixed. It was a very poor oversight of using a black colored link against a black background

**Comment by chrisvfritz** [comment]
:+1: Looks much better!
